import { Inter } from "next/font/google";
import "./globals.css";
import { WineProvider } from "./context/wineContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <WineProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </WineProvider>
  );
}
